# docker-compose.yml

#version: '3.8'
services:
 mysql:
   image: mysql:5.7
   environment:
     MYSQL_ROOT_PASSWORD: rootpassword
     MYSQL_DATABASE: testdb
     MYSQL_USER: user
     MYSQL_PASSWORD: password
   ports:
   - "3306:3306"
   volumes:
   - mysql-data:/var/lib/mysql
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 3
 webapp:
   build: ./webapp
   ports:
   - "5000:5000"
   depends_on:
     mysql:
       condition: service_healthy
   environment:
     MYSQL_HOST: mysql
     MYSQL_DATABASE: testdb
     MYSQL_USER: user
     MYSQL_PASSWORD: password
volumes:
 mysql-data:
